---
title: "EF_Tutorial_2"
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(psych)
library(moments)
library(quantmod)
library(zoo)
```
## Exercise 1

## A)
```{r warning=F, message=F}
SP500 <- read_excel("data.xlsx", sheet=1)
GBPUSD <- read_excel("data.xlsx", sheet = 2)
FFR <- read_excel("data.xlsx", sheet = 3)
# SP500
SP500 <- SP500 %>%
  mutate(daily_return = (SP500 - lag(SP500))/lag(SP500)) 

#Other option
SP500_XTS <- xts(SP500$SP500,SP500$date) # Part of Zoo library - convert to time series. quant mod library only takes time series
SP500_QNT <- dailyReturn(SP500_XTS)

na.omit(SP500)

ggplot(SP500, aes(x = date, y = daily_return)) +
  geom_line() +
  labs(title = "Daily Returns of SP500", 
       x = "Date", 
       y = "Daily Return")
# GBPUSD
GBPUSD <- GBPUSD %>%
  mutate(daily_return = (GBPUSD - lag(GBPUSD))/lag(GBPUSD)) 

ggplot(GBPUSD, aes(x = date, y = daily_return)) +
  geom_line() +
  labs(title = "Daily Returns of GBPUSD", 
       x = "Date", 
       y = "Daily Return")

# FFR
FFR <- FFR %>%
  mutate(daily_return = (EFF - lag(EFF))/lag(EFF)) 

ggplot(FFR, aes(x = date, y = daily_return)) +
  geom_line() +
  labs(title = "Daily Returns of FFR", 
       x = "Date", 
       y = "Daily Return")
```
# B)
```{r warning=F, message=F}
#SP500
SP500 <- na.omit(SP500)
acf_result <- acf(SP500$daily_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
GBPUSD <- na.omit(GBPUSD)
acf_result <- acf(GBPUSD$daily_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
FFR <- na.omit(FFR)
acf_result <- acf(FFR$daily_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# C)
```{r warning=F, message=F}
#SP500
SP500 <- na.omit(SP500)
acf_result <- acf(SP500$daily_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  mutate((1+daily_return)^365 -1) %>%
  summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
GBPUSD <- na.omit(GBPUSD)
acf_result <- acf(GBPUSD$daily_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  mutate((1+daily_return)^365 -1) %>%
  summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
FFR <- na.omit(FFR)
acf_result <- acf(FFR$daily_return, lag.max = 1, plot = FALSE)
print(FFR %>%
    mutate((1+daily_return)^365 -1) %>%
    summarize(
    mean = mean(daily_return, na.rm = TRUE),
    median = median(daily_return, na.rm = TRUE),
    sd = sd(daily_return, na.rm = TRUE),
    skewness = skewness(daily_return, na.rm = TRUE),
    kurtosis = kurtosis(daily_return, na.rm = TRUE),
    min = min(daily_return, na.rm = TRUE),
    max = max(daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# D)
```{r warning=F, message=F}
#SP500
ggplot(SP500, aes(x = daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of SP500 daily returns") 

#GBPUSD
ggplot(GBPUSD, aes(x = daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of GBPUSD daily returns") 
#FFR
ggplot(FFR, aes(x = daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of FFR daily returns") 
```
# E)
```{r warning=F, message=F}
#Join into one data frame
CovSimple <- FFR %>%
  inner_join(., SP500, join_by(date)) %>%
  inner_join(., GBPUSD,join_by(date))
#Remove and rename non-return info
CovSimple <- CovSimple %>%
  select(-c(EFF,SP500,GBPUSD,date)) %>%
  rename(EFF=daily_return, SP500 = daily_return.y, GBPUSD = daily_return.x)
CovSimple <- na.omit(CovSimple)
#Calculate & print variance-covariance
print(cov(CovSimple))
```
## Exercise 2

## A)
```{r warning=F, message=F}
# SP500
SP500 <- SP500 %>%
  mutate(log_daily_return = log((SP500)/lag(SP500)))
  
ggplot(SP500, aes(x = date, y = log_daily_return)) +
  geom_line() +
  labs(title = "Log Daily Returns of SP500", 
       x = "Date", 
       y = "Daily Return")
# GBPUSD
GBPUSD <- GBPUSD %>%
  mutate(log_daily_return = log((GBPUSD)/lag(GBPUSD))) 

ggplot(GBPUSD, aes(x = date, y = log_daily_return)) +
  geom_line() +
  labs(title = "Log Daily Returns of GBPUSD", 
       x = "Date", 
       y = "Daily Return")

# FFR
FFR <- FFR %>%
  mutate(log_daily_return = log((EFF)/lag(EFF))) 

ggplot(FFR, aes(x = date, y = daily_return)) +
  geom_line() +
  labs(title = "Log Daily Returns of FFR", 
       x = "Date", 
       y = "Daily Return")
```
# B)
```{r warning=F, message=F}
#SP500
SP500 <- na.omit(SP500)
cf_result <- acf(SP500$log_daily_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
GBPUSD <- na.omit(GBPUSD)
acf_result <- acf(GBPUSD$log_daily_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
FFR <- na.omit(FFR)
acf_result <- acf(FFR$log_daily_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# c)
```{r warning=F, message=F}
#SP500
acf_result <- acf(SP500$log_daily_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  mutate((1+log_daily_return)^365 -1) %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
acf_result <- acf(GBPUSD$log_daily_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  mutate((1+log_daily_return)^365 -1) %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
acf_result <- acf(FFR$log_daily_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  mutate((1+log_daily_return)^365 -1) %>%
  summarize(
    mean = mean(log_daily_return, na.rm = TRUE),
    median = median(log_daily_return, na.rm = TRUE),
    sd = sd(log_daily_return, na.rm = TRUE),
    skewness = skewness(log_daily_return, na.rm = TRUE),
    kurtosis = kurtosis(log_daily_return, na.rm = TRUE),
    min = min(log_daily_return, na.rm = TRUE),
    max = max(log_daily_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# D)
```{r warning=F, message=F}
#SP500
ggplot(SP500, aes(x = log_daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of SP500 log daily returns") 

#GBPUSD
ggplot(GBPUSD, aes(x = log_daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of GBPUSD log daily returns") 
#FFR
ggplot(FFR, aes(x = log_daily_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of FFR log daily returns") 
```
# E)
```{r warning=F, message=F}
#Join into one data frame
CovSimple <- FFR %>%
  inner_join(.,SP500, join_by(date)) %>%
  inner_join(., GBPUSD,join_by(date))
#Remove and rename non-return info
CovSimple <- CovSimple %>%
  select(c(log_daily_return,log_daily_return.y,log_daily_return.x)) %>%
  rename(EFF=log_daily_return, SP500 = log_daily_return.y, GBPUSD = log_daily_return.x)
CovSimple <- na.omit(CovSimple)
#Calculate & print variance-covariance
print(cov(CovSimple))
```

# f)
```{r warning=F, message=F}
ggplot(SP500, aes(x = daily_return, y = log_daily_return)) +
  geom_point() +
  labs(title = "Log Daily Returns of SP500", 
       x = "Daily Return", 
       y = "Log Daily Return")
ggplot(GBPUSD, aes(x = daily_return, y = log_daily_return)) +
  geom_point() +
  labs(title = "Log Daily Returns of GBPUSD", 
       x = "Daily Return", 
       y = "Log Daily Return")
ggplot(FFR, aes(x = daily_return, y = log_daily_return)) +
  geom_point() +
  labs(title = "Log Daily Returns of FFR", 
       x = "Daily Return", 
       y = "Log Daily Return")
```

## Exercise 3

## A)
```{r warning=F, message=F}

# SP500
SP500 <- SP500 %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(monthly_return = prod(1 + daily_return) - 1) %>%
  ungroup() %>%
  mutate(rolling_monthly_return = rollapply(daily_return + 1,
      width = 31, FUN = function(x) prod(x) - 1, align = "right", fill = NA))


SP500 <- na.omit(SP500)

#Other option
SP500_QNT <- monthlyReturn(SP500_XTS)

#Plotting
ggplot(SP500, aes(x = date, y = rolling_monthly_return)) +
  geom_line() +
  labs(title = "Monthly Returns of SP500", 
       x = "Date", 
       y = "Monthly Return")

# GBPUSD
GBPUSD <- GBPUSD %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(monthly_return = prod(1 + daily_return) - 1) %>%
  ungroup() %>%
  mutate(rolling_monthly_return = rollapply(daily_return + 1,
      width = 21, FUN = function(x) prod(x) - 1, align = "right", fill = NA))

GBPUSD <- na.omit(GBPUSD)
ggplot(GBPUSD, aes(x = date, y = rolling_monthly_return)) +
  geom_line() +
  labs(title = "Monthly Returns of GBPUSD", 
       x = "Date", 
       y = "Monthly Return")

# FFR

FFR <- FFR %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(monthly_return = prod(1 + daily_return) - 1) %>%
  ungroup() %>%
  mutate(rolling_monthly_return = rollapply(daily_return + 1,
      width = 21, FUN = function(x) prod(x) - 1, align = "right", fill = NA))

FFR <- na.omit(FFR)
ggplot(FFR, aes(x = date, y = rolling_monthly_return)) +
  geom_line() +
  labs(title = "Monthly Returns of FFR", 
       x = "Date", 
       y = "Monthly Return")
```
# B)
```{r warning=F, message=F}
#SP500
SP500 <- na.omit(SP500)
acf_result <- acf(SP500$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
GBPUSD <- na.omit(GBPUSD)
acf_result <- acf(GBPUSD$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
FFR <- na.omit(FFR)
acf_result <- acf(FFR$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# C)
```{r warning=F, message=F}
#SP500
acf_result <- acf(SP500$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  mutate((1 + rolling_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
acf_result <- acf(GBPUSD$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  mutate((1 + rolling_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
acf_result <- acf(FFR$rolling_monthly_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  mutate((1 + rolling_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_monthly_return, na.rm = TRUE),
    median = median(rolling_monthly_return, na.rm = TRUE),
    sd = sd(rolling_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_monthly_return, na.rm = TRUE),
    min = min(rolling_monthly_return, na.rm = TRUE),
    max = max(rolling_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# D)
```{r warning=F, message=F}
#SP500
ggplot(SP500, aes(x = rolling_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of SP500 monthly returns") 

#GBPUSD
ggplot(GBPUSD, aes(x = rolling_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of GBPUSD monthly returns") 
#FFR
ggplot(FFR, aes(x = rolling_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of FFR monthly returns") 
```
# E)
```{r warning=F, message=F}
#Join into one data frame
CovSimple <- FFR %>%
  inner_join(.,SP500, join_by(date)) %>%
  inner_join(., GBPUSD,join_by(date))
#Remove and rename non-return info
CovSimple <- CovSimple %>%
  select(c(rolling_monthly_return,rolling_monthly_return.x,rolling_monthly_return.y)) %>%
  rename(EFF=rolling_monthly_return, SP500 = rolling_monthly_return.y, 
         GBPUSD = rolling_monthly_return.x)
CovSimple <- na.omit(CovSimple)
#Calculate & print variance-covariance
print(cov(CovSimple))
```
## Exercise 4

## A)
```{r warning=F, message=F}

# SP500
SP500 <- SP500 %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(log_monthly_return = sum(log_daily_return)) %>%
  ungroup() %>%
  mutate(rolling_log_monthly_return = rollapply(log_daily_return, width = 31, FUN = function(x) sum(x), align = "right", fill = NA))

SP500 <- na.omit(SP500)

#Plotting
ggplot(SP500, aes(x = date, y = rolling_log_monthly_return)) +
  geom_line() +
  labs(title = "Log Monthly Returns of SP500", 
       x = "Date", 
       y = "Monthly Return")

# GBPUSD
GBPUSD <- GBPUSD %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(log_monthly_return = sum(log_daily_return)) %>%
    ungroup() %>%
  mutate(rolling_log_monthly_return = rollapply(log_daily_return, width = 21, FUN = function(x) sum(x), align = "right", fill = NA))

GBPUSD <- na.omit(GBPUSD)
ggplot(GBPUSD, aes(x = date, y = rolling_log_monthly_return)) +
  geom_line() +
  labs(title = "Log Monthly Returns of GBPUSD", 
       x = "Date", 
       y = "Monthly Return")

# FFR

FFR <- FFR %>%
  group_by(Year = year(date), Month = month(date)) %>%
  mutate(log_monthly_return = sum(log_daily_return)) %>%
  ungroup() %>%
  mutate(rolling_log_monthly_return = rollapply(log_daily_return, width = 21, FUN = function(x) sum(x), align = "right", fill = NA))

FFR <- na.omit(FFR)
ggplot(FFR, aes(x = date, y = rolling_log_monthly_return)) +
  geom_line() +
  labs(title = "Log Monthly Returns of FFR", 
       x = "Date", 
       y = "Monthly Return")
```
# B)
```{r warning=F, message=F}
#SP500
acf_result <- acf(SP500$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
acf_result <- acf(GBPUSD$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
acf_result <- acf(FFR$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# C)
```{r warning=F, message=F}
#SP500
acf_result <- acf(SP500$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(SP500 %>%
  mutate((1 + rolling_log_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))
#GBPUSD
acf_result <- acf(GBPUSD$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(GBPUSD %>%
  mutate((1 +rolling_log_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

#FFR
acf_result <- acf(FFR$rolling_log_monthly_return, lag.max = 1, plot = FALSE)
print(FFR %>%
  mutate((1 + rolling_log_monthly_return)^12 -1) %>%
  summarize(
    mean = mean(rolling_log_monthly_return, na.rm = TRUE),
    median = median(rolling_log_monthly_return, na.rm = TRUE),
    sd = sd(rolling_log_monthly_return, na.rm = TRUE),
    skewness = skewness(rolling_log_monthly_return, na.rm = TRUE),
    kurtosis = kurtosis(rolling_log_monthly_return, na.rm = TRUE),
    min = min(rolling_log_monthly_return, na.rm = TRUE),
    max = max(rolling_log_monthly_return, na.rm = TRUE),
    serial_correlation = acf_result$acf[2]
  ))

```
# D)
```{r warning=F, message=F}
#SP500
ggplot(SP500, aes(x = rolling_log_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of SP500 log monthly returns") 

#GBPUSD
ggplot(GBPUSD, aes(x = rolling_log_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of GBPUSD log monthly returns") 
#FFR
ggplot(FFR, aes(x = rolling_log_monthly_return)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of FFR log monthly returns") 
```
# E)
```{r warning=F, message=F}
#Join into one data frame
CovSimple <- FFR %>%
  inner_join(.,SP500, join_by(date)) %>%
  inner_join(., GBPUSD,join_by(date))
#Remove and rename non-return info
CovSimple <- CovSimple %>%
  select(c(rolling_log_monthly_return, rolling_log_monthly_return.y, rolling_log_monthly_return.x)) %>%
  rename(EFF=rolling_log_monthly_return, SP500 = rolling_log_monthly_return.y, GBPUSD = rolling_log_monthly_return.x)
CovSimple <- na.omit(CovSimple)
#Calculate & print variance-covariance
print(cov(CovSimple))
```

# f)
```{r warning=F, message=F}
#SP500
ggplot(SP500, aes(x = rolling_monthly_return, y = rolling_log_monthly_return)) +
  geom_point() +
  labs(title = "Simple vs Log Monthly Returns of SP500", 
       x = "Monthly return", 
       y = "Log Monthly return")
#GDPUSD
ggplot(GBPUSD, aes(x = rolling_monthly_return, y = rolling_log_monthly_return)) +
  geom_point() +
  labs(title = "Simple vs Log Monthly Returns of GDPUSD", 
       x = "Monthly return", 
       y = "Log Monthly return")
#FFR
ggplot(FFR, aes(x = rolling_monthly_return, y = rolling_log_monthly_return)) +
  geom_point() +
  labs(title = "Simple vs Log Monthly Returns of FFR", 
       x = "Monthly return", 
       y = "Log Monthly return")
```

Exercise 5
```{r warning=F, message=F}
#A)
set.seed(1234)
mu <- 0
sigma <- 1
n <- 1000
ndist <- data.frame(x = rnorm(n, mu, sigma))

ggplot(ndist, aes(x = x)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of Normal Distribution")

#B)
# Set the parameters
mu <- 0  # mean
theta <- 1  # scale
nu <- 5  # degrees of freedom

# Generate random samples from a standardized t-distribution
tdist <- data.frame(x = mu + theta * rt(n, df = nu))

ggplot(tdist, aes(x = x)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of T Distribution")

#C)
# Set the parameters
mu <- 0  # mean
theta <- 1  # scale
nu <- 30  # degrees of freedom

# Generate random samples from a standardized t-distribution
tdist <- data.frame(x = mu + theta * rt(n, df = nu))

ggplot(tdist, aes(x = x)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of T Distribution")
#D)
# Set the parameters
mu <- 0  # mean
theta <- 1  # scale
nu <- 5  # degrees of freedom
epsilon <- .5 #skew

# Generate random samples from a standardized t-distribution
tdist <- data.frame(x = mu + theta * rt(n, df = nu, ncp = epsilon))

ggplot(tdist, aes(x = x)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of T Distribution")

#E)
# Set the parameters
mu <- 0  # mean
theta <- 1  # scale
nu <- 5  # degrees of freedom
epsilon <- 2 #skew

# Generate random samples from a standardized t-distribution
tdist <- data.frame(x = mu + theta * rt(n, df = nu, ncp = epsilon))

ggplot(tdist, aes(x = x)) +
    geom_histogram(bins = 100, 
                   color = "black", 
                   fill = "white") +
    ylab("") + 
    xlab("") +
    ggtitle("Histogram of T Distribution")

# 
n <- 10000
rand_unifs<- data.frame(x = runif(n, min = 0, max = 10)) #runif will give us a uniform distribution 
rand_unifs %>%
  ggplot(aes(x=x)) + 
    geom_histogram(binwidth=1) 

rand_poiss<- data.frame(x = rpois(n, lambda = 4.5)) #rpoiss will give us a poisson distribution with the arguments n and lambda
rand_poiss %>%
  ggplot(aes(x=x)) + 
    geom_histogram(binwidth=1) 





```